/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodorderingsystem;

/**
 *
 * @author Istehad
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class homepage extends javax.swing.JFrame {
     Connection con=null;
     ResultSet re=null;
     PreparedStatement pst=null;
     Show_Menu jtRowData=new Show_Menu();
    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
        //con=DBConnect.ConnectDB();
        Update_table();
        Fillcombo();
    }
    private void Update_table(){
         
        try{
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://localhost:1433;user=sa;password=emon108481;" +
            "databaseName=new;";  
        
        String sql="select name , type , location , status from Restaurant";
        con = DriverManager.getConnection(connectionUrl);
            pst=con.prepareStatement(sql);
        re=pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(re));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
    
    private void Fillcombo(){
        try{
           String sql="select*from student";
           pst=con.prepareStatement(sql);
           re=pst.executeQuery();
           
           while(re.next()){
               String name =re.getString("firstname");
               //combobox.addItem(name);
           }
           
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("      SEARCH");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(321, 321, 321)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        
       try{
            String sql="select distinct Restaurant.Name,Restaurant.Type,Restaurant.Location,Restaurant.Status "
                    + "from Restaurant full outer join Menu "
                    + "on Restaurant.R_ID=Menu.R_id "
                    + "where Restaurant.Location=?"; 
            pst=con.prepareStatement(sql);
            pst.setString(1,search.getText());
            re=pst.executeQuery(); 
            jTable2.setModel(DbUtils.resultSetToTableModel(re));
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
      
       
                /*try{
                    String sql="select distinct Restaurant.Name,Restaurant.Type,Restaurant.Location,Restaurant.Status "
                            + "from Restaurant full outer join Menu "
                            + "on Restaurant.R_ID=Menu.R_id "
                            + "where Restaurant.Location=?"; 
                    pst=con.prepareStatement(sql);
                    pst.setString(1,search.getText());
                    re=pst.executeQuery(); 
                    jTable2.setModel(DbUtils.resultSetToTableModel(re));

                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }*/
       
        
        
        
        /*try{
           
           
            String sql="select distinct Restaurant.Name,Restaurant.Type,Restaurant.Location,Restaurant.Status from Restaurant full outer join Menu on Restaurant.R_ID=Menu.R_id where Restaurant.Name=?"; 
            pst=con.prepareStatement(sql);
            pst.setString(1,search.getText());
             re=pst.executeQuery(); 
              jTable2.setModel(DbUtils.resultSetToTableModel(re));*/
            /*if(re.next()){
                String add1=re.getString("id");
                jTextField1.setText(add1);
                String add2=re.getString("firstname");
                jTextField2.setText(add2);
                String add3=re.getString("lastname");
                jTextField3.setText(add3);
                String add4=re.getString("userid");
                jTextField4.setText(add4);
        }*/
        //}
      /*  catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }*/
        /*try{
           
           
            String sql="select distinct Restaurant.Name,Restaurant.Type,Restaurant.Location,Restaurant.Status from Restaurant full outer join Menu on Restaurant.R_ID=Menu.R_id where Restaurant.Location=?"; 
            pst=con.prepareStatement(sql);
            pst.setString(1,search.getText());
             re=pst.executeQuery(); 
              jTable2.setModel(DbUtils.resultSetToTableModel(re));
    */
            /*if(re.next()){
                String add1=re.getString("id");
                jTextField1.setText(add1);
                String add2=re.getString("firstname");
                jTextField2.setText(add2);
                String add3=re.getString("lastname");
                jTextField3.setText(add3);
                String add4=re.getString("userid");
                jTextField4.setText(add4);
        }*/
      //  }
       /* catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }*/
       /* try{
           
           
            String sql="select distinct Restaurant.Name,Restaurant.Type,Restaurant.Location,Restaurant.Status from Restaurant full outer join Menu on Restaurant.R_ID=Menu.R_id where Restaurant.Type=?"; 
            pst=con.prepareStatement(sql);
            pst.setString(1,search.getText());
             re=pst.executeQuery(); 
              jTable2.setModel(DbUtils.resultSetToTableModel(re));
*/
            /*if(re.next()){
                String add1=re.getString("id");
                jTextField1.setText(add1);
                String add2=re.getString("firstname");
                jTextField2.setText(add2);
                String add3=re.getString("lastname");
                jTextField3.setText(add3);
                String add4=re.getString("userid");
                jTextField4.setText(add4);
        }*/
       /* }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
*/
        /*try{
           
           
            String sql="select distinct Restaurant.Name,Restaurant.Type,Restaurant.Location,Restaurant.Status from Restaurant full outer join Menu on Restaurant.R_ID=Menu.R_id where Menu.Name=?"; 
            pst=con.prepareStatement(sql);
            pst.setString(1,search.getText());
             re=pst.executeQuery(); 
              jTable2.setModel(DbUtils.resultSetToTableModel(re));
*/
            /*if(re.next()){
                String add1=re.getString("id");
                jTextField1.setText(add1);
                String add2=re.getString("firstname");
                jTextField2.setText(add2);
                String add3=re.getString("lastname");
                jTextField3.setText(add3);
                String add4=re.getString("userid");
                jTextField4.setText(add4);
        }*/
       /* }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }*/
        
        
         
         /*try{
           
           
            String sql="select Restaurant.Name,Restaurant.Type,Restaurant.Location,Restaurant.Status from Restaurant join Menu on Restaurant.R_ID=Menu.R_id where Restaurant.Name=?"; 
            pst=con.prepareStatement(sql);
            pst.setString(1,search.getText());
             re=pst.executeQuery();           
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } */
        
        
        
        
    }//GEN-LAST:event_searchKeyReleased

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
 int index = jTable2.getSelectedRow();
          TableModel model= jTable2.getModel();
          //int value = Integer.parseInt(model.getValueAt(index,0).toString());
         // new Show_Menu(value);
          String name = model.getValueAt(index,0).toString();
          String location = model.getValueAt(index,2).toString();
          jtRowData.setVisible(true);
          jtRowData.pack();
          jtRowData.setLocationRelativeTo(null);
          jtRowData.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
          jtRowData.jTextField1.setText(name);
          jtRowData.jTextField2.setText(location);        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    
         int index = jTable1.getSelectedRow();
          TableModel model= jTable1.getModel();
          //int value = Integer.parseInt(model.getValueAt(index,0).toString());
         // new Show_Menu(value);
          String name = model.getValueAt(index,0).toString();
          String location = model.getValueAt(index,2).toString();
          jtRowData.setVisible(true);
          jtRowData.pack();
          jtRowData.setLocationRelativeTo(null);
          jtRowData.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
          jtRowData.jTextField1.setText(name);
          jtRowData.jTextField2.setText(location); // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
home hm = new home();
hm.setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
